export const SET_PRODUCTS = "SET_PRODUCTS"
export const UNSHIFT_PRODUCT = "UNSHIFT_PRODUCT"
export const GET_PROCUCTS_STATUS = "GET_PROCUCTS_STATUS"
export const POST_PROCUCT_STATUS = "POST_PROCUCT_STATUS"
